### ISSUE TITLE
[镜像请求] Rust 包管理仓库 crate.io

### ISSUE THREAD

**Issue by Kherrisan** [seu-mirrors/issues#1]
### 项目名称与简介

希望能增加 Rust 包管理仓库的镜像，方便广大 Rust 开发者使用 crate 包~

### 上游地址与镜像方法

上游地址的话可以是 [https://crates.io](https://crates.io)，当然也可以用国内的 [mirrors.ustc.edu.cn](https://mirrors.ustc.edu.cn/crates.io-index/) 或者字节的 [rsproxy](https://rsproxy.cn/)，可选项还挺多的。
镜像方法的话可以参考这个 [希望能增加 https://crates.io 的镜像](https://github.com/ustclug/mirrorrequest/issues/16)

**Comment by idawnlight** [comment]
目前已借由 [sjtug/mirror-clone](https://github.com/sjtug/mirror-clone) 完成初始同步，可以通过编辑 `~/.cargo/config.toml` 试用：

```toml

[source]

[source.mirror]
registry = "sparse+https://mirrors.seu.edu.cn/crates.io-index/"

[source.crates-io]
replace-with = "mirror"
```

请注意，当前仅支持稀疏索引，镜像站暂时不提供 git 服务。
